# Generated by Django 5.2 on 2025-05-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("Personal Travel", "Personal Travel"),
                            ("Air Travel", "Air Travel"),
                            ("Electricity", "Electricity"),
                            ("Purchased Goods and Services", "Purchased Goods"),
                        ],
                        max_length=100,
                    ),
                ),
                ("co2e", models.FloatField()),
                ("scope", models.IntegerField()),
                ("category", models.IntegerField(null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("Personal Travel", "Personal Travel"),
                            ("Air Travel", "Air Travel"),
                            ("Electricity", "Electricity"),
                            ("Purchased Goods and Services", "Purchased Goods"),
                        ],
                        max_length=100,
                    ),
                ),
                ("lookup_identifiers", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=50)),
                ("co2e", models.FloatField()),
                ("scope", models.IntegerField()),
                ("category", models.IntegerField(null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
